[build]
  functions = "dist/functions"
  publish = "public"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify-handler"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200